### ISSUE TITLE
Invalid Zip - Not executable

### ISSUE THREAD

**Issue by Hacnstein** [eltos/PasteIntoFile#43]
The portable version will not open, it says invalid zip file? When I tried on another computer is thinks .2_portable is a file extension, if I changed it to EXE is doesn't run either.
![portable](https://github.com/eltos/PasteIntoFile/assets/72718369/3283def3-0e48-4fe7-a1dc-bd7b51e65221)

...

**To Reproduce**

1. ...
2. ...

```
...
```

**Error message**

```
...
```

**Screenshots**

![error](https://github.com/eltos/PasteIntoFile/assets/72718369/455c2d1e-788b-40a7-aef8-866b18cebc70)

**Environment**

- App version: 5.2
- OS: Win1022H2 x64
- ...

**Solution approach / workarounds**

...

**Comment by eltos** [comment]
GitHub action was creating a `.tar.gz` file and named it `.zip`.  
Should be fixed now. Patched the previous versions manually.
