### ISSUE TITLE
v5.3 default image to jpg not remebered

### ISSUE THREAD

**Issue by barn852** [eltos/PasteIntoFile#45]
v5.3
I am not able to set the default image format to jpg.

I tried on both portable and install version.
Also tried manually to set it in the PasteIntoFile.exe.config and the settings.config in the program directory (both portable and install versions). but image is always saved as png by default.

Works well for v5.2 - no problem with the default image format (as it is in the description, after changing once the image format, next time it is remembered)

ps: windows 10

**Comment by eltos** [comment]
Thanks for reporting this regression, fixed with v5.3.1

**Comment by barn852** [comment]
Thanks man. That was fast!
