### ISSUE TITLE
Format specifier for day of the year

### ISSUE THREAD

**Issue by Crunchbits** [eltos/PasteIntoFile#49]
**Description**
A new format specifier for the day of the year (1-365). This would be very useful to use instead of using month+day of the month. It's shorter most of the time throughout the year and so it's easier to read at a glance.

**Specification and constraints**
I've seen some programs use j as the variable for the day of the year but I don't know if that's a common standard.
Also would prefer if there was no leading zeros on single and double digits, but I suppose two versions could be made if desired.

Thanks for the useful program!

**Comment by eltos** [comment]
The program uses the format specifiers provided by .NET framework as described here:
https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

Day-of-year is not part of this standard and would require some custom implementation.

This is the relevant code in [Dialog.cs](https://github.com/eltos/PasteIntoFile/blob/c455353fd6e46229ead24de4bae44ab3c34eb0de/PasteIntoFile/Dialog.cs#L184):
```csharp
public static string formatFilenameTemplate(string template, DateTime timestamp, int count) {
    return String.Format(template, timestamp, count);
}
```

Feel free to submit a PR if anybody likes to implement this.

**Comment by faizahfarzana** [comment]
Hi, I'm interested to work on this issue. For clarification, the current default file name format is like "2024-07-01 17-53-00" and you want to remove mm-dd part and use the day of year like this "2024-156 17-53-00"?

**Comment by Crunchbits** [comment]
Agreed that the default template should stay the same. Day of year would just be a variable that could be added to the custom template.

**Comment by faizahfarzana** [comment]
Thank you both for the clarification. I'll assess this and get to work.
