### ISSUE TITLE
Pasting Raw File after Using Copy Button in GitHub Web UI Results in Error

### ISSUE THREAD

**Issue by pa-0** [eltos/PasteIntoFile#58]
#### To Reproduce

1. Select the _Copy_ button (shown in top right corner of webpage in screenshot) to get the contents of the dracula windows terminal theme (JSON) (Click expand button below to see screenshot and text contents)

    <details><summary><strong>SHOW/HIDE JSON file contents</strong></summary>
    
    ![msedge_EAOOnfsLzY](https://github.com/user-attachments/assets/1657a034-8538-4412-a40f-cc5d7109c72c)

    ```json   
    {
      "name": "Dracula",
      "cursorColor": "#F8F8F2",
      "selectionBackground": "#44475A",
      "background": "#282A36",
      "foreground": "#F8F8F2",
      "black": "#21222C",
      "blue": "#BD93F9",
      "cyan": "#8BE9FD",
      "green": "#50FA7B",
      "purple": "#FF79C6",
      "red": "#FF5555",
      "white": "#F8F8F2",
      "yellow": "#F1FA8C",
      "brightBlack": "#6272A4",
      "brightBlue": "#D6ACFF",
      "brightCyan": "#A4FFFF",
      "brightGreen": "#69FF94",
      "brightPurple": "#FF92DF",
      "brightRed": "#FF6E6E",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#FFFFA5"
    }
    ```
  
    </details>

2. Open Paste Into File and try saving the contents into a file with either .json or .txt extension (did not try any others) and get the error shown in the same screenshot above.

#### Environment

- App version: latest
- OS: Windows 11 Enterprise 64-bit build: 22631.4317

**Comment by eltos** [comment]
Thanks @pa-0 for reporting, was actually already fixed in main, backported to 5.3 now:
https://github.com/eltos/PasteIntoFile/releases/tag/v5.3.4
