### ISSUE TITLE
Remember last save location

### ISSUE THREAD

**Issue by pa-0** [eltos/PasteIntoFile#59]
Regardless of where clipboard contents are saved, on next run, the Folder/File dialog defaults to the Desktop instead of the last save location.  It would be convenient if it were to open the last save location, or at least offer the option to.

**Comment by eltos** [comment]
The main usage of this app is to paste files into the folder you currently view in the opened explorer window (or if none is open paste onto the desktop).
Remembering the last folder is not useful.

Depending on your use case the batch mode or #56 might be what you are looking for. If not, then please provide a detailed explanation of your use case and propose a behaviour that works with the main usage.
