### ISSUE TITLE
Every Thought of Implementing This Into Microsoft PowerToys? 

### ISSUE THREAD

**Issue by Bj007pro** [eltos/PasteIntoFile#63]
I assume you know what [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/) is, so I wont go into detail. But this being added to one of many other great features (and other open source applications) to Microsoft PowerToys would make this tool a lot easy to use and would haven't to be a separate running application.

**Comment by eltos** [comment]
There is a longstanding open issue in the Power Toys Repo about adding PasteIntoFile: https://github.com/microsoft/PowerToys/issues/3098

I don't have ambitions doing that. It'll be a lot of work to adopt and probably require rewriting a large portion of the app. I don't see a benefit that would motivate me going through that hassle. I don't know what you mean by "lot easy to use" and I also don't see a problem with having a separate application. On the contrary, having it separate allows people to use this lightweight tool without having to install the full PowerToys suite. So unless there are some better arguments I'll close this as "not planned".
